[2025-02-25T18:36:14.091+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-25T18:36:14.179+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tugas_kita.wait_for_new_data manual__2025-02-25T18:28:26.482492+00:00 [queued]>
[2025-02-25T18:36:14.226+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tugas_kita.wait_for_new_data manual__2025-02-25T18:28:26.482492+00:00 [queued]>
[2025-02-25T18:36:14.230+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 7
[2025-02-25T18:36:14.488+0000] {taskinstance.py:2889} INFO - Executing <Task(SqlSensor): wait_for_new_data> on 2025-02-25 18:28:26.482492+00:00
[2025-02-25T18:36:14.536+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=50433) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-25T18:36:14.549+0000] {standard_task_runner.py:72} INFO - Started process 50490 to run task
[2025-02-25T18:36:14.561+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'tugas_kita', 'wait_for_new_data', 'manual__2025-02-25T18:28:26.482492+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/tugas_akhir.py', '--cfg-path', '/tmp/tmp4pnfkb08']
[2025-02-25T18:36:14.572+0000] {standard_task_runner.py:105} INFO - Job 96: Subtask wait_for_new_data
[2025-02-25T18:36:14.855+0000] {task_command.py:467} INFO - Running <TaskInstance: tugas_kita.wait_for_new_data manual__2025-02-25T18:28:26.482492+00:00 [running]> on host d22a487e6b55
[2025-02-25T18:36:15.197+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Dion Rikki' AIRFLOW_CTX_DAG_ID='tugas_kita' AIRFLOW_CTX_TASK_ID='wait_for_new_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T18:28:26.482492+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-25T18:28:26.482492+00:00'
[2025-02-25T18:36:15.204+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-25T18:36:15.210+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-25T18:36:15.214+0000] {logging_mixin.py:190} INFO - Current task name:wait_for_new_data state:running start_date:2025-02-25 18:36:14.181834+00:00
[2025-02-25T18:36:15.217+0000] {logging_mixin.py:190} INFO - Dag name:tugas_kita and current dag run status:running
[2025-02-25T18:36:15.221+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-25T18:36:15.297+0000] {base.py:84} INFO - Retrieving connection 'mysql_default'
[2025-02-25T18:36:15.309+0000] {sql.py:101} INFO - Poking: SELECT COUNT(*) FROM tugas_akhir_sensordata WHERE timestamp >= NOW() - INTERVAL 5 MINUTE (with parameters None)
[2025-02-25T18:36:15.364+0000] {base.py:84} INFO - Retrieving connection 'mysql_default'
[2025-02-25T18:36:15.390+0000] {sql.py:553} INFO - Running statement: SELECT COUNT(*) FROM tugas_akhir_sensordata WHERE timestamp >= NOW() - INTERVAL 5 MINUTE, parameters: None
[2025-02-25T18:36:15.401+0000] {sql.py:562} INFO - Rows affected: 1
[2025-02-25T18:36:15.630+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-02-25T18:36:15.635+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-25T18:36:15.732+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-25T18:36:15.866+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-25T18:36:15.872+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
