[2025-02-25T15:36:13.199+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-25T15:36:13.335+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: triggered_by_new_data.get_data_from_db manual__2025-02-25T15:21:38.673440+00:00 [queued]>
[2025-02-25T15:36:13.405+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: triggered_by_new_data.get_data_from_db manual__2025-02-25T15:21:38.673440+00:00 [queued]>
[2025-02-25T15:36:13.412+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-25T15:36:13.791+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): get_data_from_db> on 2025-02-25 15:21:38.673440+00:00
[2025-02-25T15:36:13.828+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'triggered_by_new_data', 'get_data_from_db', 'manual__2025-02-25T15:21:38.673440+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/tugas_akhir.py', '--cfg-path', '/tmp/tmpx91d90uf']
[2025-02-25T15:36:13.829+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=56165) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-25T15:36:13.833+0000] {standard_task_runner.py:105} INFO - Job 67: Subtask get_data_from_db
[2025-02-25T15:36:13.835+0000] {standard_task_runner.py:72} INFO - Started process 56239 to run task
[2025-02-25T15:36:14.632+0000] {task_command.py:467} INFO - Running <TaskInstance: triggered_by_new_data.get_data_from_db manual__2025-02-25T15:21:38.673440+00:00 [running]> on host 15e5b1e5ccc7
[2025-02-25T15:36:16.024+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Dion Rikki' AIRFLOW_CTX_DAG_ID='triggered_by_new_data' AIRFLOW_CTX_TASK_ID='get_data_from_db' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T15:21:38.673440+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-25T15:21:38.673440+00:00'
[2025-02-25T15:36:16.039+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-25T15:36:16.044+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-25T15:36:16.047+0000] {logging_mixin.py:190} INFO - Current task name:get_data_from_db state:running start_date:2025-02-25 15:36:13.342470+00:00
[2025-02-25T15:36:16.061+0000] {logging_mixin.py:190} INFO - Dag name:triggered_by_new_data and current dag run status:running
[2025-02-25T15:36:16.063+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-25T15:36:16.072+0000] {logging_mixin.py:190} INFO - üîç [1] Menghubungkan ke database MySQL...
[2025-02-25T15:36:16.508+0000] {logging_mixin.py:190} INFO - üìä Data yang diambil dari MySQL:
   Humidity  Moisture
0      88.0      25.8
1      88.0      25.8
2      88.0      25.8
[2025-02-25T15:36:16.716+0000] {logging_mixin.py:190} INFO - ‚úÖ Data berhasil disimpan ke XCom. Jumlah baris: 3
[2025-02-25T15:36:16.726+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-25T15:36:16.805+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-25T15:36:16.824+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=triggered_by_new_data, task_id=get_data_from_db, run_id=manual__2025-02-25T15:21:38.673440+00:00, execution_date=20250225T152138, start_date=20250225T153613, end_date=20250225T153616
[2025-02-25T15:36:17.224+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-25T15:36:17.245+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-25T15:36:17.261+0000] {logging_mixin.py:190} INFO - Dag name:triggered_by_new_data queued_at:2025-02-25 15:21:38.723821+00:00
[2025-02-25T15:36:17.306+0000] {logging_mixin.py:190} INFO - Task hostname:15e5b1e5ccc7 operator:PythonOperator
[2025-02-25T15:36:17.440+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-25T15:36:17.881+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-25T15:36:18.524+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-25T15:36:18.849+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
