[2025-04-21T13:52:00.176+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-21T13:52:00.262+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: perbaikan_skripsi.predict_and_store_result scheduled__2025-04-21T13:46:00+00:00 [queued]>
[2025-04-21T13:52:00.335+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: perbaikan_skripsi.predict_and_store_result scheduled__2025-04-21T13:46:00+00:00 [queued]>
[2025-04-21T13:52:00.341+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-04-21T13:52:00.759+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): predict_and_store_result> on 2025-04-21 13:46:00+00:00
[2025-04-21T13:52:00.810+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4396) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-21T13:52:00.818+0000] {standard_task_runner.py:72} INFO - Started process 4512 to run task
[2025-04-21T13:52:00.880+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'perbaikan_skripsi', 'predict_and_store_result', 'scheduled__2025-04-21T13:46:00+00:00', '--job-id', '10594', '--raw', '--subdir', 'DAGS_FOLDER/tugas_akhir.py', '--cfg-path', '/tmp/tmpgerodd3h']
[2025-04-21T13:52:00.892+0000] {standard_task_runner.py:105} INFO - Job 10594: Subtask predict_and_store_result
[2025-04-21T13:52:01.659+0000] {task_command.py:467} INFO - Running <TaskInstance: perbaikan_skripsi.predict_and_store_result scheduled__2025-04-21T13:46:00+00:00 [running]> on host a9576c91091e
[2025-04-21T13:52:02.466+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Dion Rikki' AIRFLOW_CTX_DAG_ID='perbaikan_skripsi' AIRFLOW_CTX_TASK_ID='predict_and_store_result' AIRFLOW_CTX_EXECUTION_DATE='2025-04-21T13:46:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-21T13:46:00+00:00'
[2025-04-21T13:52:02.491+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-21T13:52:02.496+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-21T13:52:02.500+0000] {logging_mixin.py:190} INFO - Current task name:predict_and_store_result state:running start_date:2025-04-21 13:52:00.265807+00:00
[2025-04-21T13:52:02.504+0000] {logging_mixin.py:190} INFO - Dag name:perbaikan_skripsi and current dag run status:running
[2025-04-21T13:52:02.507+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-21T13:52:02.516+0000] {logging_mixin.py:190} INFO - üîç [2] Memproses data dan melakukan prediksi...
[2025-04-21T13:52:02.717+0000] {logging_mixin.py:190} INFO - ‚úÖ Data siap diproses: 1 baris
    id  Temperature  Humidity  ...  nitrogen phosphorous potassium
0  952         25.3      84.0  ...       0.0         0.0       0.0

[1 rows x 9 columns]
[2025-04-21T13:52:02.718+0000] {logging_mixin.py:190} INFO - üìù Menyesuaikan nama kolom dengan model training...
[2025-04-21T13:52:02.722+0000] {logging_mixin.py:190} INFO - üîß Melakukan encoding kategori Soil_Type dan Crop_Type...
[2025-04-21T13:52:02.735+0000] {logging_mixin.py:190} INFO - üß† Menyiapkan fitur untuk prediksi...
[2025-04-21T13:52:02.741+0000] {logging_mixin.py:190} INFO - ü§ñ Menjalankan model prediksi...
[2025-04-21T13:52:02.808+0000] {logging_mixin.py:190} INFO - ‚úÖ Prediksi selesai:
    id predicted_fertilizer
0  952             10-10-10
[2025-04-21T13:52:02.815+0000] {logging_mixin.py:190} INFO - üíæ Menyimpan hasil ke tabel fertilizer_predictions...
[2025-04-21T13:52:03.122+0000] {logging_mixin.py:190} INFO - ‚ùå Error saat menyimpan ke database: (pymysql.err.IntegrityError) (1062, "Duplicate entry '952' for key 'fertilizer_predictions.sensor_data_id'")
[SQL: INSERT INTO fertilizer_predictions (sensor_data_id, predicted_fertilizer, created_at) VALUES (%(sensor_data_id)s, %(predicted_fertilizer)s, %(created_at)s)]
[parameters: {'sensor_data_id': 952, 'predicted_fertilizer': '10-10-10', 'created_at': datetime.datetime(2025, 4, 21, 13, 52, 2, 823549)}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2025-04-21T13:52:03.137+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-21T13:52:03.175+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-21T13:52:03.178+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=perbaikan_skripsi, task_id=predict_and_store_result, run_id=scheduled__2025-04-21T13:46:00+00:00, execution_date=20250421T134600, start_date=20250421T135200, end_date=20250421T135203
[2025-04-21T13:52:03.661+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-21T13:52:03.663+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-21T13:52:03.669+0000] {logging_mixin.py:190} INFO - Dag name:perbaikan_skripsi queued_at:2025-04-21 13:47:00.105841+00:00
[2025-04-21T13:52:03.670+0000] {logging_mixin.py:190} INFO - Task hostname:a9576c91091e operator:PythonOperator
[2025-04-21T13:52:03.799+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-21T13:52:03.937+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-21T13:52:03.959+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
