[2025-04-22T06:30:07.603+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-22T06:30:07.753+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: perbaikan_skripsi.predict_and_store_result scheduled__2025-04-22T06:21:00+00:00 [queued]>
[2025-04-22T06:30:07.936+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: perbaikan_skripsi.predict_and_store_result scheduled__2025-04-22T06:21:00+00:00 [queued]>
[2025-04-22T06:30:07.955+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-04-22T06:30:08.177+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): predict_and_store_result> on 2025-04-22 06:21:00+00:00
[2025-04-22T06:30:08.266+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=46217) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-22T06:30:08.269+0000] {standard_task_runner.py:72} INFO - Started process 46277 to run task
[2025-04-22T06:30:08.272+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'perbaikan_skripsi', 'predict_and_store_result', 'scheduled__2025-04-22T06:21:00+00:00', '--job-id', '4247', '--raw', '--subdir', 'DAGS_FOLDER/tugas_akhir.py', '--cfg-path', '/tmp/tmp9rzu9zru']
[2025-04-22T06:30:08.278+0000] {standard_task_runner.py:105} INFO - Job 4247: Subtask predict_and_store_result
[2025-04-22T06:30:08.691+0000] {task_command.py:467} INFO - Running <TaskInstance: perbaikan_skripsi.predict_and_store_result scheduled__2025-04-22T06:21:00+00:00 [running]> on host a38b69ba8f8a
[2025-04-22T06:30:09.723+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Dion Rikki' AIRFLOW_CTX_DAG_ID='perbaikan_skripsi' AIRFLOW_CTX_TASK_ID='predict_and_store_result' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T06:21:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-22T06:21:00+00:00'
[2025-04-22T06:30:09.762+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-22T06:30:09.768+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-22T06:30:09.779+0000] {logging_mixin.py:190} INFO - Current task name:predict_and_store_result state:running start_date:2025-04-22 06:30:07.764910+00:00
[2025-04-22T06:30:09.780+0000] {logging_mixin.py:190} INFO - Dag name:perbaikan_skripsi and current dag run status:running
[2025-04-22T06:30:09.789+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-22T06:30:09.792+0000] {logging_mixin.py:190} INFO - üîç [2] Memproses data dan melakukan prediksi...
[2025-04-22T06:30:09.949+0000] {logging_mixin.py:190} INFO - ‚úÖ Data siap diproses: 1 baris
    id  Temperature  Humidity  ...  nitrogen phosphorous potassium
0  198         25.3      86.0  ...       0.0         0.0       0.0

[1 rows x 9 columns]
[2025-04-22T06:30:09.955+0000] {logging_mixin.py:190} INFO - üìù Menyesuaikan nama kolom dengan model training...
[2025-04-22T06:30:09.964+0000] {logging_mixin.py:190} INFO - üîß Melakukan encoding kategori Soil_Type dan Crop_Type...
[2025-04-22T06:30:09.982+0000] {logging_mixin.py:190} INFO - üß† Menyiapkan fitur untuk prediksi...
[2025-04-22T06:30:09.987+0000] {logging_mixin.py:190} INFO - ü§ñ Menjalankan model prediksi...
[2025-04-22T06:30:10.111+0000] {logging_mixin.py:190} INFO - ‚úÖ Prediksi selesai:
    id predicted_fertilizer
0  198             10-10-10
[2025-04-22T06:30:10.115+0000] {logging_mixin.py:190} INFO - üíæ Menyimpan hasil ke tabel fertilizer_predictions...
[2025-04-22T06:30:10.242+0000] {logging_mixin.py:190} INFO - ‚ùå Error saat menyimpan ke database: (pymysql.err.IntegrityError) (1062, "Duplicate entry '198' for key 'fertilizer_predictions.sensor_data_id'")
[SQL: INSERT INTO fertilizer_predictions (sensor_data_id, predicted_fertilizer, created_at) VALUES (%(sensor_data_id)s, %(predicted_fertilizer)s, %(created_at)s)]
[parameters: {'sensor_data_id': 198, 'predicted_fertilizer': '10-10-10', 'created_at': datetime.datetime(2025, 4, 22, 6, 30, 10, 122666)}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2025-04-22T06:30:10.248+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-22T06:30:10.316+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-22T06:30:10.318+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=perbaikan_skripsi, task_id=predict_and_store_result, run_id=scheduled__2025-04-22T06:21:00+00:00, execution_date=20250422T062100, start_date=20250422T063007, end_date=20250422T063010
[2025-04-22T06:30:10.415+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-22T06:30:10.420+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-22T06:30:10.421+0000] {logging_mixin.py:190} INFO - Dag name:perbaikan_skripsi queued_at:2025-04-22 06:22:00.729877+00:00
[2025-04-22T06:30:10.423+0000] {logging_mixin.py:190} INFO - Task hostname:a38b69ba8f8a operator:PythonOperator
[2025-04-22T06:30:10.482+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-22T06:30:10.650+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T06:30:10.663+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
